
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=321321
    ports:
      - 5433:5432

  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_DSN=postgres://postgres:321321@db:5432/postgres?sslmode=disable
    ports:
      - 8082:8080
